### ISSUE TITLE
Why no rumble?

### ISSUE THREAD

**Issue by barolo** [TheDrHax/ds4drv-cemuhook#2]
It's natively supported by kernel why it isn't exposed by this driver?

Recently dolphin emulator enabled cemuhook protocol, but I'm quite confused by what's going on there, since gyro/accel is supposed to be working natively...

**Comment by TheDrHax** [comment]
UDP server is not completely implemented yet. Right now it can only send events from controller to cemuhook, but not the other way around.

I'm not even sure that cemuhook's UDP protocol supports this type of events. For example, [steam-gyro-for-cemuhook](https://github.com/FrogTheFrog/steam-gyro-for-cemuhook/blob/master/src/backend/lib/udp-server/index.ts) implements only 3 types of incoming packets: `VersionReq`, `ListPorts` and `PadDataReq`. None of them seem to contain any information about feedback and all of them are implemented in this driver (although perhaps not completely).

I will try to inspect traffic between driver and Cemu using Wireshark. Maybe there are more types of packets, that are not covered by other implementations yet.

**Comment by TheDrHax** [comment]
Hmm... UDP server should [print a warning](https://github.com/TheDrHax/ds4drv-cemuhook/blob/master/ds4drv/servers/udp.py#L93) every time it receives a packet with unknown or incorrect header. I haven't seen any warnings during several walkthroughs of BotW. Either cemuhook doesn't support rumble or it needs to be enabled by appropriate UDP response or in one of config files.

**Comment by barolo** [comment]
> Hmm... UDP server should [print a warning](https://github.com/TheDrHax/ds4drv-cemuhook/blob/master/ds4drv/servers/udp.py#L93) every time it receives a packet with unknown or incorrect header. I haven't seen any warnings during several walkthroughs of BotW. Either cemuhook doesn't support rumble or it needs to be enabled by appropriate UDP response or in one of config files.

I'm totally in the dark about this. Currently I'm testing/using your driver with git dolphin and Skyward Sword [ it works surprisingly good and using DS4 as motion/steering control is.. weird ], maybe it would be easier to pull out something from this/ ask them?

**Comment by barolo** [comment]
@TheDrHax It turns out that in Dolphin you can mix and match stuff via Virtual Xinput source provided via DSU serwers, and pick where rumble comes out. In other words, it works.
Thus my question seems irrelevant...

**Comment by epigramx** [comment]
It appears to work by default now! I used latest wine git (with a patch required to run vulkan, but that should be irrelevant). I believe it's a new feature of wine (for XInput emulation).

**Comment by barolo** [comment]
@epigramx I'm using wine 5 patched for vulkan, and the weird thing is that cemu only works with ds4drv for me now, rumble still doesn't seem to work though. Which game are you testing this with?

**Comment by epigramx** [comment]
@barolo I only used the current wine git (I guess that version is called "devel" in distributions) which I compiled with the default instructions (and I only added a patch to make vulkan work which should be irrelevant for this feature). It works by selecting XInput in Cemu (Controller "2" for some reason) and then turning on the Rumble slider at the bottom. It's not very surprising since I knew wine only just started adding XInput so I'm pretty sure many distributions will not have a wine with the feature.

**Comment by epigramx** [comment]
There's a good chance it depends on the controller. I used a DS4 via bluetooth. I do not know the details of wine how far the support goes but I'm pretty sure XInput emulation is a relatively recent addition/it was being actively developed recently.

**Comment by barolo** [comment]
I'm on Gentoo, wine 5.x is very recent, I'm using Xinput in Cemu, are you sure that you're using ds4drv? Do you have both gyro/motion and rumble at once?
I'm Iriny wired DS4 v2

**Comment by epigramx** [comment]
@barolo As I said, only wine's XInput emulation was needed. I reported that in relation to the Cemu hook part of ds4drv-cemuhook. Cemu currently only works via wine and I know ds4drv does not have rumble support.

**Comment by barolo** [comment]
I'm not sure what you're saying; does it work together with ds4drv/motion input or not? I don't care otherwise

**Comment by epigramx** [comment]
Of course. Cemu has an XInput option at controllers with a rumble slider at the bottom. Only caveat is that you must also the "Also use for buttons/axes" option of Cemuhook in Cemu options to let ds4drv-cemuhook take over for the keys too since for some reason it always takes over the buttons of XInput emulation (though I guess ds4drv-cemuhook could be edited to not do that functionality at all).

**Comment by barolo** [comment]
@It does work indeed! and I had it set up correctly.... Just that button remapping in cemu's input window  doesn't work in such configuration and this mislead me/got me confused.
Thank you for the info, Star Fox Zero is going to be much funnier now

**Comment by barolo** [comment]
@epigramx 
It does work indeed! and I had it set up correctly.... Just that button remapping in cemu's input window  doesn't work in such configuration and this mislead me/got me confused.
Thank you for the info, Star Fox Zero is going to be much funnier now

**Comment by barolo** [comment]
Is it possible to enable blow mic/swap screen special shortcuts in such configuration? motion from dsu + rumble from xinput? @epigramx  @TheDrHax
